### ISSUE TITLE
Change FloatType to DoubleType

### ISSUE THREAD

**Issue by USCYuandaDu** [jpmml/jpmml-sparkml-xgboost#6]
Hi @vruusmann ,
Since it is kind of defensive process, maybe we could change FloatType to DoubleType here? 
https://github.com/jpmml/jpmml-sparkml-xgboost/blob/0feb4d4e45e94cae868e108015f85bf64d2dea0a/src/main/java/org/jpmml/sparkml/xgboost/BoosterUtil.java#L68
Bests,
Yuanda

**Comment by USCYuandaDu** [comment]
In that way, we do not have to transform the data type and more reasonable since at most time, the type is double.

**Comment by USCYuandaDu** [comment]
And we should also change float to double here too ? 
https://github.com/jpmml/jpmml-xgboost/blob/6a557d317b3cbc64f2e8c287cf937b54a81dc888/src/main/java/org/jpmml/xgboost/RegTree.java#L138-L144

**Comment by USCYuandaDu** [comment]
@vruusmann

**Comment by vruusmann** [comment]
> Maybe we could change FloatType to DoubleType here?

Not allowed - the XGBoost algorithm is encoding and evaluating tree splits using the `float` datatype. If you change it to double, then some tree splits may start evaluating wrong (eg. `float` would send the sample to the left, whereas `double` would send it to the right).

> we do not have to transform the data type and more reasonable since at most time, the type is double.

If you load a CSV file into Apache Spark ML, then numeric columns will be `double` by default.

I wonder how did you manage to get `float` columns into your dataframe - did you already force-cast them from `double` to `float`? If you did, then simply remove that code, so that `double` columns stay `double` columns.

The JPMML-SparkML-XGBoost is performing programmatic cast here:
https://github.com/jpmml/jpmml-sparkml-xgboost/blob/master/src/main/java/org/jpmml/sparkml/xgboost/BoosterUtil.java#L79

**Comment by USCYuandaDu** [comment]
@vruusmann ，yes, I forced them to float, since I do not want the transformationDictionary works so that the field name of SimplePredict won't be wrapped with float()    
Got it.
Bests,
Yuanda

**Comment by vruusmann** [comment]
> I do not want the transformationDictionary works so that the field name of SimplePredict won't be wrapped with float()

You could try "refactoring" PMML documents programmatically. The idea is to replace all `float(x)` references (DerivedField) with `x` references (DataField).
